@startuml
'Direccion of the diagram'
left to right direction
'Used style'
skinparam backgroundColor #F5E6CC
'Classes'
skinparam classBackgroundColor #A7C7E7
skinparam classBorderColor #000000
skinparam shadowing true
skinparam roundcorner 15
'Titles'
skinparam classFontColor #000000
skinparam classFontStyle bold
'Relationships'
skinparam classArrowColor #4CAF50
skinparam classArrowThickness 2
skinparam classArrowFontColor black
skinparam classArrowFontSize 11
skinparam nodesep 20
skinparam ranksep 5




' Entities'
class Client{
    id
    name
    username
    email
    password
    phone
    address
    profilePicture
    birthdate
    country
    Vet
    Pet

}

class Pet {
    id
    species
    age
    status
    gender
    MedicalHistory
    Client
    Vet
}

class MedicalHistory{
    id
    medical_description
    Pet
    Vet
}

class Vet {
    id
    name
    email
    phone
    address
    Pet
    Client
    Clinic
}

class VaccineType{
    id_vaccine
    name
    price
}

class PetVaccine{
    id_pet
    id_vaccine
    application_date
}

class Clinic {
    id
    name
    location
    workingHours
    Vet
}

class Cart{
    id_cart
    total_products
    total_price
    CartItem
}

class CartItem{
    id_item_cart
    quantity
}

class Product{
    id_product
    name
    product_description
    price
    discountedPrice
    pictureProduct
    CartItem
}

class ProductCategory{
    id_category
    name
    description
}


'Relationships'
Client "1" --- "N" Pet : owns >
Pet "1" -- "1" MedicalHistory : has >
Vet "1" -- "N" Client : serves >
Clinic "1" -- "N" Vet : employs >
Cart "1" -- "N" CartItem : has >
CartItem "N" -- "1" Product : contains >
PetVaccine "N" -- "1" Pet : relates >
PetVaccine "N" -- "1" VaccineType : relates >
Cart "1" -- "1" Client : has >
Product "N" -- "N" ProductCategory : relates >





@enduml